name: Deploy

on:
  push:
    branches: [devops/deno_deploy, main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build Web
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: npm ci
      - run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "devs-playing-poker"
          entrypoint: "./server/server.ts"
