name: Preview Deployment

on:
  pull_request:
    branches: [main]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run format

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: format
    defaults:
      run:
        working-directory: ./web
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build Web
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "devs-playing-poker"
          root: server
          entrypoint: "./server.ts"
          import-map: deno.jsonc
